Repository elastic/azure-vm-extension, pull requests merged in 2021-08, with the labels that each got.

#27 [automation] Update Elastic stack release version [6.8.17, 7.13.3, 7.13.4, 7.14.0]
  .ci/Jenkinsfile
  .ci/its.groovy
Labels: automation, dependency

#28 ATs: Fix 503 errors
  test/ats/validate.py
Labels: Team:Automation, flaky-test

#30 503 returns a different output
  test/ats/validate.py
Labels: Team:Automation

#29 Store ElasticAgent logs with the azure vm extension execution
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/docker/azure-vm-tools/Dockerfile
  .ci/docker/azure-vm-tools/entrypoint.sh
  .ci/its.groovy
  test/terraform/README.md
  test/terraform/main.tf
Labels: Team:Automation
